title: "[Help] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Stuck on something? Ask here. Check the [README](https://github.com/nelsonramosua/miniAI/blob/main/README.md) and [existing discussions](https://github.com/nelsonramosua/miniAI/discussions) first.

  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      placeholder: I'm trying to train a model on...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      placeholder: |
        I ran:
        [./miniAI train --dataset digits --data]...
        
        And got:
        Error: ...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Building / compiling
        - Training a model
        - Testing / loading a model
        - Phrase recognition
        - Benchmarking
        - Docker
        - CI/CD
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS & compiler
      placeholder: "e.g. macOS 14, Apple Silicon, gcc 13"
    validations:
      required: true