title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea for miniAI that isn't quite a formal feature request? Discuss it here first. If it is, do a feature request.

  - type: textarea
    id: idea
    attributes:
      label: The Idea
      description: Describe the idea in plain terms.
      placeholder: What if miniAI could...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Neural network core
        - New dataset / recognition type
        - CLI / usability
        - Performance
        - Image processing
        - CI/CD / tooling
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful? What problem does it solve?
      placeholder: This would help because...
    validations:
      required: true

  - type: textarea
    id: sketch
    attributes:
      label: Rough sketch (optional)
      description: Any pseudocode, diagrams, or examples of how it might work.
      placeholder: |
        ./miniAI new-command --flag
        
        Or in code:
        void myNewFunction(...) { ... }